name: push image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Image tag Version'
        required: true

env:
  IMAGE_NAME: dobolinux/cs16-server-launcher
  IMAGE_VERSION: ${{ startsWith(github.ref, 'refs/tags/') && ${{ steps.bump-semver.outputs.new_version }} || github.event.inputs.image_version }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - uses: actions/checkout@v3

      - if: startsWith(github.ref, 'refs/tags/')
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - if: startsWith(github.ref, 'refs/tags/')
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: minor

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            latest
            ${{ env.IMAGE_VERSION }}

      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: true
          tags: '${{ steps.meta.outputs.tags }}'
          build-args: |
            BUILD_DATE=${{ }}
            BUILD_VERSION=${{ env.IMAGE_VERSION }}
            VCS_REF=${{ env.IMAGE_VERSION }}